routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('color.index');
});

Route::prefix('/admin', ['middleware'=>'auth'])->group(function (){
    Route::resource('/order','Admin\OrderController');
    Route::resource('/orderItem','Admin\OrderItemController');
    Route::resource('/material','Admin\MaterialController');
    Route::resource('/materialColor','Admin\MaterialColorController');
    Route::resource('/style','Admin\StyleController');
    Route::resource('/color','Admin\ColorController');
    Route::resource('/product','Admin\ProductController');
    Route::get('/excelExport/{order}','Admin\OrderItemController@excelExport')->name('excelExport');
    Route::post('/detail/{orderItem}','Admin\DetailController@detail')->name('detail');

});

resources/views/admin/layots/app.blade.php
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{$title}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{{asset('assets/images/icon/favicon.ico')}}">
    <link rel="stylesheet" href="{{asset('assets/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/font-awesome.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/themify-icons.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/metisMenu.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/slicknav.min.css')}}">
    <!-- amchart css -->
{{--    <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all"/>--}}
    <!-- others css -->
    <link rel="stylesheet" href="{{asset('assets/css/typography.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/default-css.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/styles.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/responsive.css')}}">
    <!-- modernizr css -->
    <script src="{{asset('assets/js/vendor/modernizr-2.8.3.min.js')}}"></script>
</head>

<body>
<!--[if lt IE 8]>
<!--<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade-->
<!--    your browser</a> to improve your experience.</p>-->
<![endif]-->
<!-- preloader area start -->
<div id="preloader">
    <div class="loader"></div>
</div>
<!-- preloader area end -->
<!-- page container area start -->
<div class="page-container">
    @include('admin.layots.sideBar')
        <div class="main-content-inner">

            @yield('content')

        </div>
    </div>
    <!-- main content area end -->
    <!-- footer area start-->
    <footer>
        <div class="footer-area">
            <p>© Copyright {{date('Y')}}.</p>
        </div>
    </footer>
    <!-- footer area end-->
</div>
<!-- page container area end -->
<!-- jquery latest version -->
<!-- jquery latest version -->
<script src="{{asset('assets/js/jquery.3.2.1.min.js')}}"></script>

{{--<script src="{{asset('assets/js/vendor/jquery-2.2.4.min.js')}}"></script>--}}
<!-- bootstrap 4 js -->
<script src="{{asset('assets/js/popper.min.js')}}"></script>
<script src="{{asset('assets/js/bootstrap.min.js')}}"></script>
<script src="{{asset('assets/js/owl.carousel.min.js')}}"></script>
<script src="{{asset('assets/js/metisMenu.min.js')}}"></script>
<script src="{{asset('assets/js/jquery.slimscroll.min.js')}}"></script>
<script src="{{asset('assets/js/jquery.slicknav.min.js')}}"></script>

{{--<!-- start chart js -->--}}
{{--<script src="{{asset('assets/js/Chart.min.js')}}"></script>--}}
{{--<!-- start highcharts js -->--}}
{{--<script src="{{asset('assets/js/highcharts.js')}}"></script>--}}
{{--<!-- start zingchart js -->--}}
{{--<script src="{{asset('assets/js/zingchart.min.js')}}"></script>--}}

{{--<script src="{{asset('assets/js/amcharts.js')}}"></script>--}}
{{--<script src="{{asset('assets/js/serial.js')}}"></script>--}}
{{--<script src="{{asset('assets/js/export.min.js')}}"></script>--}}
{{--<script src="{{asset('assets/js/light.js')}}"></script>--}}
{{--<!-- all line chart activation -->--}}
{{--<script src="{{asset('assets/js/line-chart.js')}}"></script>--}}
{{--<!-- all pie chart -->--}}
{{--<script src="{{asset('assets/js/pie-chart.js')}}"></script>--}}
<!-- others plugins -->
<script src="{{asset('assets/js/plugins.js')}}"></script>
<script src="{{asset('assets/js/scripts.js')}}"></script>
<script src="{{asset('assets/js/jquery.form.js')}}"></script>
<script src="{{asset('assets/js/site.js')}}"></script>

@yield('script')
</body>
</html>

resources/views/admin/layots/sideBar.blade.php
<div class="sidebar-menu">
    <div class="sidebar-header">
        <div class="logo">
            <a href="{{route('color.index')}}"><img src="{{asset('assets/images/icon/logo.png')}}" alt="logo"></a>
        </div>
    </div>
    <div class="main-menu">
        <div class="menu-inner">
            <nav>
                <ul class="metismenu" id="menu">
{{--                    <li class="{{($activ==1)?'active':''}}">--}}
{{--                        <a href="{{route('color.index')}}" aria-expanded="true"><i class="ti-dashboard"></i><span>Админ</span></a>--}}
                        {{--                        <ul class="collapse">--}}
                        {{--                            <li class="active"><a href="#">Active Menu Item</a></li>--}}
                        {{--                            <li><a href="#">Menuitem 2</a></li>--}}
                        {{--                            <li><a href="#">Menuitem 3</a></li>--}}
                        {{--                        </ul>--}}
{{--                    </li>--}}
                    <li class="{{($activ==1)?'active':''}}"><a href="{{route('color.index')}}"><i class="ti-agenda "></i><span>Цвет</span></a>
                    </li>
                    <li class="{{($activ==2)?'active':''}}"><a href="{{route('material.index')}}"><i class="ti-layers-alt"></i><span>Материал</span></a>
                    </li>
                    <li class="{{($activ==3)?'active':''}}"><a href="{{route('materialColor.index')}}"><i class="ti-tag"></i><span>Цвет материалов</span></a>
                    </li>
                    <li class="{{($activ==4)?'active':''}}"><a href="{{route('style.index')}}"><i class="ti-briefcase"></i><span>Стиль</span></a>
                    </li>
                    <li class="{{($activ==5)?'active':''}}"><a href="{{route('product.index')}}"><i
                                    class="ti-bookmark-alt"></i><span>Продукт</span></a></li>
                    <li class="{{($activ==6)?'active':''}}"><a href="{{route('order.index')}}"><i
                                    class="ti-bookmark-alt"></i><span>Заказ</span></a></li>
                    {{--                    <li>--}}
                    {{--                        <a href="javascript:void(0)" aria-expanded="true"><i class="fa fa-align-left"></i>--}}
                    {{--                            <span>Multi--}}
                    {{--                                        level menu</span></a>--}}
                    {{--                        <ul class="collapse">--}}
                    {{--                            <li><a href="#">Item level (1)</a></li>--}}
                    {{--                            <li><a href="#">Item level (1)</a></li>--}}
                    {{--                            <li><a href="#" aria-expanded="true">Item level (1)</a>--}}
                    {{--                                <ul class="collapse">--}}
                    {{--                                    <li><a href="#">Item level (2)</a></li>--}}
                    {{--                                    <li><a href="#">Item level (2)</a></li>--}}
                    {{--                                    <li><a href="#">Item level (2)</a></li>--}}
                    {{--                                </ul>--}}
                    {{--                            </li>--}}
                    {{--                            <li><a href="#">Item level (1)</a></li>--}}
                    {{--                        </ul>--}}
                    {{--                    </li>--}}
                </ul>
            </nav>
        </div>
    </div>
</div>
<!-- sidebar menu area end -->
<!-- main content area start -->
<div class="main-content">
    <!-- page title area start -->
    <div class="page-title-area">
        <div class="row align-items-center">
            <div class="col-md-6 col-sm-6 clearfix">
                <div class="nav-btn pull-left">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
                <div class="breadcrumbs-area clearfix">
                    <h4 class="page-title pull-left">Админа</h4>
                    <ul class="breadcrumbs pull-left">
{{--                        <li><a href="{{route('color.index')}}">Главная</a></li>--}}
                        <li><span>{{$title}}</span></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6 clearfix">
                <div class="user-profile pull-right">
                    <img class="avatar user-thumb" src="{{asset('assets/images/author/avatar.png')}}" alt="avatar">
                    <h4 class="user-name dropdown-toggle" data-toggle="dropdown">{{$user }} <i
                        ></i></h4>
                    {{--                    class="fa fa-angle-down"--}}
                    {{--                    <div class="dropdown-menu">--}}
                    {{--                        <a class="dropdown-item" href="#">Message</a>--}}
                    {{--                        <a class="dropdown-item" href="#">Settings</a>--}}
                    {{--                        <a class="dropdown-item" href="#">Log Out</a>--}}
                    {{--                    </div>--}}
                </div>
            </div>
        </div>
    </div>